security:
  encoders:
    App\Entity\User:
      algorithm: bcrypt

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    refresh:
      pattern: ^/api/token/refresh
      stateless: true
      anonymous: true

    login:
      pattern: ^/api/login
      stateless: true
      anonymous: true

    register:
      pattern: ^/api/register
      stateless: true
      anonymous: true

    api:
      pattern: ^/api
      stateless: true
      provider: app_user_provider
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator

    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: true

  access_control:
    - { path: ^/api/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
